export const WindowsIcons = {
  MyComputer: "💻",
  Documents: "📁",
  Music: "🎵",
  Games: "🎮",
  Internet: "🌐",
  Email: "📧",
  Settings: "⚙️",
  Help: "❓",
  Search: "🔍",
  User: "👤",
  Calendar: "📅",
  Pictures: "🖼️",
  Video: "🎥",
  Download: "⬇️",
  Upload: "⬆️",
  Favorite: "⭐",
  Warning: "⚠️",
  Info: "ℹ️",
  Error: "❌",
  Success: "✅",
  Lock: "🔒",
  Unlock: "🔓",
  Print: "🖨️",
  Save: "💾",
  Edit: "✏️",
  Cut: "✂️",
  Copy: "📋",
  Paste: "📌",
  Undo: "↩️",
  Redo: "↪️",
  Refresh: "🔄",
  Home: "🏠",
  Chat: "💬",
  Close: "❌",
  Minimize: "➖",
  Maximize: "⬜",
  Terminal: "🖥️",
  Windows: "🪟",
  Poolsuite: "🌊",
  Notes: "📝",
}

